# Generated by Django 4.0.3 on 2022-04-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_delete_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='dob',
        ),
    ]
