# Generated by Django 4.0.3 on 2022-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=11),
        ),
    ]
